### ISSUE TITLE
와우.. 이런 엄청난 작업을... :)

### ISSUE THREAD

**Issue by rickiepark** [python/python-docs-ko#1]
@flowdas 
그런데 docs.python.org 에 아직 ko 링크가 안생기는 건 번역 작업이 완료가 안되어서 그런건가요?

**Comment by flowdas** [comment]
요건은 모두 충족했고, 일단 빌드 프로세스에는 들어갔습니다.

https://docs.python.org/ko/3.6/ <https://docs.python.org/ko/3.6/>

여기 까지는 들어갔는데, 언어선택기 변경을 담당자가 벌써 몇달째 질질 끌고 있구만...

**Comment by flowdas** [comment]
요건은 모두 충족된 것 같은데, 절차가 더디게 진행되네요. 빌드 프로세스에는 포함되어서 https://docs.python.org/ko/3.6/ 는 만들어지고 있어요. 문제는 언어스위치 연결이 몇달째 지연되고 있는것이지요...

**Comment by rickiepark** [comment]
숟가락 얹을 만한 문서가 있는지 살펴봐야 겠군요. 작업하는 가이드라인이 따로 있나요?

**Comment by flowdas** [comment]
아직 공동작업자가 없어서 따로 가이드라인을 작성하지는 않았지만 머리속에 들어있는 것은 있습니다. 이제 가이드라인을 만들때가 된 것 같군요. 대체로 일관성을 유지하기 위한 내용들입니다. 가령 Glossary 에 등장하는 용어들은 어떤식으로 ReST 마크업해야하는지, Glossary 에 등장하지 않는 용어들의 표준 번역어 사전같은 것들입니다.
라이브러리 레퍼런스 중에서 관심있는 녀석들을 작업하는것이 편할겁니다. 참고로 라이브러리 레퍼런스의 4~5장은 커밋하지 않은 번역이 있으니 피하는 것이 좋을듯. 챕터별로 이슈를 등록해드릴까요?

**Comment by rickiepark** [comment]
네 챕터별 이슈나 가이드라인을 정리해 주시면 이후 참여자들에게 도움이 될 것 같습니다. 저도 한 술 거들께요. :)

**Comment by rickiepark** [comment]
넵 알겠습니다. 링크 추가해 달라고 다시 요청해 보세요. 필시 까먹고 있을 듯. :)

**Comment by JulienPalard** [comment]
Hi, I would gladly join the conversation about docs.python.org but I can't follow in your language, if the matter is about the link still not appearing in docs.python.org, there is still some missing symlinks I don't have the rights to add manually in production, and didn't had time to look at it. Back from holidays, I'm looking at it.

**Comment by JulienPalard** [comment]
https://github.com/python/cpython/pull/6627 has been merged, being backported to 3.7.

**Comment by flowdas** [comment]
I can also find Korean links in version 3.7. Thank you, Jullien.

Now, I'm going to get into the 3.7 "What's New" translation. However, at the end there is a section on PEP 545, which does not mention Korean translation. If I translate this part in Korean, I think it will produce some contradictory situation.

**Comment by corona10** [comment]
@rickiepark 
백포트 패치가 3.7까지만 진행되서 3.6도 올렸으니 머지되면 반영될 것 같습니다.

**Comment by JulienPalard** [comment]
@flowdas Yes it's typical to find situations where modifying upstream first make more sense, typically when you find typos/errors upstream (yes it happen). This is one. One of us can PR on `whatsnew/3.7.rst` to fix this.

**Comment by flowdas** [comment]
Perfect.

@Julien
I have a question. Can I apply for a public mailing list for python.org as a conversation space between Korean translation teams? We need a space where we can talk in Korean and keep records for members to join later. Github issues do not seem to be the space to be used for this purpose. How is the French team doing?

**Comment by flowdas** [comment]
@corona10 감사합니다. 시간 나실 때 번역도 부탁드립니다. :-)

**Comment by rickiepark** [comment]
@corona10 감사합니다. :)

**Comment by corona10** [comment]
@flowdas @rickiepark
시간 날 때 번역해도 참여해보겠습니다.

**Comment by JulienPalard** [comment]
ko switcher now visible in https://docs.python.org/3.6/

**Comment by rickiepark** [comment]
Thanks a lot! @JulienPalard 
I will close this issue and open new issue if necessary. :)
