### ISSUE TITLE
translate c-api/intro.po

### ISSUE THREAD

**Issue by flowdas** [python/python-docs-ko#34]

**Comment by emiatej9** [comment]
번역 하겠습니다.

**Comment by flowdas** [comment]
예, 부탁드립니다.

**Comment by NovemberOscar** [comment]
2020년 6월인 지금도 미번역 상태인데 제가 번역해도 괜찮을까요?

**Comment by flowdas** [comment]
감사합니다. 부탁드리겠습니다.

**Comment by NovemberOscar** [comment]
# 번역 현황

- [x] Introduction
- [x] Coding standards
- [x] Include Files
- [x] Useful macros
- [x] Objects, Types and Reference Counts
	- [ ] Reference Counts -- 현재 진행중인 부분
		- [ ] Reference Count Details
	- [ ] Types
- [ ] Exceptions
- [ ] Embedding Python
- [ ] Debugging Builds

**Comment by flowdas** [comment]
수고하셨습니다.
