### ISSUE TITLE
translate library/unittest.mock.po

### ISSUE THREAD

**Issue by flowdas** [python/python-docs-ko#374]

**Comment by unace** [comment]
이것도 unittest와 같이 제가 번역해보겠습니다.

**Comment by unace** [comment]
@flowdas 님, 죄송하지만 제가 개인적인 사정으로 더 이상 작업을 못할 것 같습니다. 연말까지 unittest 테스트 관련 모듈을 다 완료하려고 했는데 생각보다 쉽지 않네요. 약속을 지키지 못해서 죄송합니다. 다음에 기회되면 다시 참여하도록 하겠습니다.

**Comment by flowdas** [comment]
그 동안 작업해주신 것만으로도 큰 도움이 되었습니다. 다음에 여유 생기시면 또 부탁드릴께요. 감사합니다.
