### ISSUE TITLE
translate library/unittest.po

### ISSUE THREAD

**Issue by flowdas** [python/python-docs-ko#375]

**Comment by unace** [comment]
unittest는 제가 번역해보겠습니다.

**Comment by flowdas** [comment]
이슈세개 합하면 분량이 만만치않아서(진척률 2.1% 규모입니다), 아무도 선뜻 나서지 않을 것 같았는데. 감사합니다. 파일하나 끝날 때마다 PR 보내주세요. asyncio 마무리되면 제가 하려고 하던건데, 덕분에 다른 것으로 넘어가도 될 것 같습니다.
