### ISSUE TITLE
build.py error on Windows

### ISSUE THREAD

**Issue by waterple** [python/python-docs-ko#435]
sphinx-build: error: unrecognized arguments :ko 
를 오류로 뱉습니다..
(Wndows 8.1 , python 3.6.4)

**Comment by waterple** [comment]
혹시 윈도우에서 테스트 안하셨나요..?

**Comment by flowdas** [comment]
아직 윈도우는 지원하지 않습니다.

**Comment by waterple** [comment]
그럼 반드시 리눅스가 필요한가요..?

**Comment by flowdas** [comment]
그게 제일 간단할 것 같습니다. 윈도우를 지원하거나 다른 더 편한 방법도 강구해보겠습니다.

**Comment by waterple** [comment]
일단  build.py 의 build()에서 옵션들을 작은따옴표로 묶어주니까 관련 에러들은 사라지는데요,
autobuild-stable-html은 아무리 구글링을 해도 찾아지지 않습니다... 정확히 무슨 옵션인가요??

**Comment by flowdas** [comment]
cpython/Doc/Makefile target 중 하나입니다.

**Comment by flowdas** [comment]
```
git clone git@github.com:python/cpython.git
```
은 되시나요?

**Comment by caerang** [comment]
@flowdas 
```
git clone git@github.com:python/cpython.git
```
위 명령어도 접근 권한이 없어서 안됩니다. 일단 임시로 ssh가 아니라 https 로 build.py 코드 수정하고 실행해 봤는데, 프로젝트 다운로드는 되는데
```python
Not building; 3.8.0a0 is not a release version.
make: *** [autobuild-stable-html] Error 1
Traceback (most recent call last):
  File "./build.py", line 57, in <module>
    main()
  File "./build.py", line 53, in main
    build()
  File "./build.py", line 48, in build
    chdir=doc_dir)
  File "./build.py", line 22, in shell
    return subprocess.check_call(cmd, **opts)
  File "/Users/hyeongdo/.pyenv/versions/3.6.5/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'make VENVDIR=../../venv SPHINXOPTS='-D locale_dirs=../locale -D language=ko -D gettext_compact=0' autobuild-stable-html' returned non-zero exit status 2.
```
위와 같은 에러가 발생해서 일단 중단한 상태에요.

**Comment by flowdas** [comment]
@caerang 

github 에 ssh 설정을 하지 않으셔서 생기는 문제 같습니다. ssh 설정을 하시거나, build.py 에 있는 git@github.com:python/cpython.git 를 https url 로 바꾸고 실행해보세요. 방금 보내주신 에러는 build.py 가 하는 브랜치 설정이 이루어지지 않아서 생기는 에러입니다. 이미 clone 한 cpython 디렉토리는 삭제하셔야합니다.

**Comment by caerang** [comment]
@flowdas 

네, 말씀처럼 ssh 키 등록하니까 잘 동작합니다. 감사합니다.
