### ISSUE TITLE
오타 수정이 필요합니다.

### ISSUE THREAD

**Issue by yoonsanghyuk** [python/python-docs-ko#593]
https://docs.python.org/ko/3/tutorial/appetite.html

여러분은 이런 적업들을 유닉스 셸 스크립트나 
- 적업 -> 작업

![image](https://user-images.githubusercontent.com/21325672/55455814-0d160580-5620-11e9-9894-b116c077417f.png)

**Comment by flowdas** [comment]
수정 했습니다. 감사합니다.
