### ISSUE TITLE
python3.7 version re.split() module bug

### ISSUE THREAD

**Issue by KateJeong95** [python/python-docs-ko#597]
text = "Some File Num10 example.txt"
re.split("\s*", text)

The result of the regular expression in version 3.7 changed from the version 3.6 result

python3.6 version result :  
['Some', 'File', 'Num10', 'example.txt']

python3.7 version result : 
['', 'S', 'o', 'm', 'e', '', 'F', 'i', 'l', 'e', '', 'N', 'u', 'm', '1', '0', '', 'e', 'x', 'a', 'm', 'p', 'l', 'e', '.', 't', 'x', 't', '']

**Comment by flowdas** [comment]
So, what should we do?

**Comment by KateJeong95** [comment]
Is that the desired result in re.split in python3.7? If not, it should be corrected as in 3.6.

**Comment by KateJeong95** [comment]
Sorry. It looks like you've entered the link incorrectly. I will contact you for the bug in question elsewhere.

**Comment by flowdas** [comment]
It is an intended change in 3.7. Since 3.7, it's possible to split on a pattern that could match an empty string. To get the same result as in 3.6, you can use ``r'\s+'``.
