### ISSUE TITLE
3.7 tutorial list example code error

### ISSUE THREAD

**Issue by accidentlywoo** [python/python-docs-ko#598]
```
squares = list(map(lambda x: x**2, range(10)))
```
this example code has error
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-54-343efe911d44> in <module>
----> 1 squares = list(map(lambda x: x**2, range(10)))

TypeError: 'list' object is not callable

**Comment by flowdas** [comment]
- The example is not wrong. Look for any changes to the definition of list.
- This repository only deals with translations. Please check the original contents first.

**Comment by accidentlywoo** [comment]
thank you!
