### ISSUE TITLE
`square brackets: 꺾쇠괄호` 를 `대괄호`로 변경 요청드립니다.

### ISSUE THREAD

**Issue by ujuc** [python/python-docs-ko#600]
해당 단어인 `square bracket`의 경우, `꺾쇠괄호` 보다는 `대괄호` 맞을 것으로 보여집니다.

https://ko.wikipedia.org/wiki/%EA%B4%84%ED%98%B8

찾다보니 국립 국어원에서 트윈한 내용이 있군요.

https://twitter.com/urimal365/status/309905847658610688

괄호로 우리말 샘에서는 문장 부호중 `대괄호`로 나옵니다.
https://opendict.korean.go.kr/dictionary/view?word_no=33855&sense_no=525044

`꺾쇠괄호`의 경우, 출판에서 사용하는 것을 가르키는군요.

https://opendict.korean.go.kr/dictionary/view?word_no=54647&sense_no=107793

국립국어원에서는 다음과 같이 검색이됩니다.

https://www.korean.go.kr/front/search/searchAllList.do

**Comment by flowdas** [comment]
여러 링크들을 종합해보면 [] 를 '꺽쇠괄호'라고 부르는 것이 틀린 표현은 아닌 것 같은데요. '대괄호'가 더 쉽고, 널리 받아들여지는 표현이라는 뜻인가요?

**Comment by ujuc** [comment]
출판일 경우, `꺽쇠괄호`라고 표현하는것같은데... 지금은 `꺾쇠괄호` 되어있기도하고, 수학적 용어 표현할때, 대괄호로 하는게 더 이해가 쉬울듯 합니다.

**Comment by flowdas** [comment]
합리적인 선택인 것 같습니다. 다른 의견 없으면 일괄 변경하겠습니다.

**Comment by flowdas** [comment]
변경했습니다.
