### ISSUE TITLE
`raw` 에대한 번역

### ISSUE THREAD

**Issue by ujuc** [python/python-docs-ko#602]
`raw` 단어를 `날`로 번역하자고 말씀해주셨던데.
너무 직설적입니다.

[papago](https://papago.naver.com/?sk=auto&tk=ko&hn=0&st=raw%20data)에서는 `raw data`를 `미가공 데이터`로 추천을 하는것을 봐서는 `미가공`이나 이전 번역이 한 `원시` 데이터로 하는게 좋을꺼같습니다.

**Comment by flowdas** [comment]
어디에서 누가 한 말을 뜻하시는 것인지 잘 모르겠습니다. 또, '이전 번역'이 뭔가요?

**Comment by ujuc** [comment]
@flowdas 혼란스럽게 말씀드린점 죄송합니다.

1. https://www.flowdas.com/pages/python-docs-ko.html 여기에 `raw`를 `날`로 번역하자고 되어있습니다.
2. `이전 번역`이라고 표현한 부분은 다른 분들이 번역한 책에서는 `원시`로 번역하여 나온 책들이 있어서 그렇게 표현했습니다.

**Comment by flowdas** [comment]
raw 는 평범한 단어여서 문맥에 따라 적당히 번역하면되지, 언제나 ``날`` 을 고집할 필요는 없어보입니다. 일관성을 쥬지할 필요가 있는 곳은 문법 요소를 직접 지칭하는 ``raw string`` 인데, 이 때 ``미가공 문자열`` 은 좋은 선택이 아닙니다. 또한 ``원시 문자열`` 도 좋은 선택은 아닌 것으로 보입니다.

**Comment by ujuc** [comment]
`raw` 가 참... 번역하기 어려운 단어 중 하나네요...
