### ISSUE TITLE
translate faq/design.po

### ISSUE THREAD

**Issue by flowdas** [python/python-docs-ko#85]

**Comment by CSwhisky** [comment]
I'd like to work on it.

**Comment by flowdas** [comment]
Welcome to join us.

**Comment by djohnkang** [comment]
It seems like this project is not in progress. Can I work on faq?

**Comment by flowdas** [comment]
Yes, please.

**Comment by flowdas** [comment]
@djohnkang Are you still working on this issue? If you have no plans to work on it anytime soon, I will do it.
